version: '3'

services:
  clickhouse:
    image: clickhouse:24.11-jammy
    hostname: clickhouse
    restart: always
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "9123:8123"
      - "10000:9000"
      - "10009:9009"

  rabbitmq:
    image: rabbitmq:3.13.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASSWORD=${RABBITMQ_DEFAULT_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports: 
      - "15672:15672"
      - "5672:5672"

volumes:
  clickhouse_data:
    driver: local
    driver_opts:
      type: none
      device: ./shared/${NODE_ENV}/clickhouse
      o: bind
  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      device: ./shared/${NODE_ENV}/rabbitmq
      o: bind
    