version: '2'

services:
  clickhouse:
    image: bitnami/clickhouse:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - statistic-network
    volumes:
      - type: bind
        source: ./tsv/hits_v1.tsv
        target: /bitnami/clickhouse/tsv/hits_v1.tsv
      - /etc/conf.d/clickhouse.config.xml:/bitnami/clickhouse/etc/conf.d/config.xml:ro
    ports:
      - "8002:9000"
      - "9123:8123"

networks:
  statistic-network:
    driver: bridge